const _generate_enum_docs = quote
    for enum_name in mousetrap.enums
        enum = getproperty(mousetrap, enum_name)
        values = []
        for value_name in mousetrap.enum_values
            if typeof(getproperty(mousetrap, value_name)) <: enum
                push!(values, value_name)
            end
        end

        value_string = ""
        for i in 1:length(values)
            value_string *= "    :" * string(values[i])
            if i != length(values)
                value_string *= ","
            end
            value_string *= "\n"
        end

        println("""
        @document $enum_name enum_docs(:$enum_name,
            "TODO", [
        $value_string])""")

        for value in values
           println("@document $value \"TODO\"")
        end

        println()
    end
end

@document Alignment enum_docs(:Alignment,
    "TODO", [
    :ALIGNMENT_CENTER,
    :ALIGNMENT_END,
    :ALIGNMENT_START
])
@document ALIGNMENT_CENTER "TODO"
@document ALIGNMENT_END "TODO"
@document ALIGNMENT_START "TODO"

@document BlendMode enum_docs(:BlendMode,
    "TODO", [
    :BLEND_MODE_ADD,
    :BLEND_MODE_MAX,
    :BLEND_MODE_MIN,
    :BLEND_MODE_MULTIPLY,
    :BLEND_MODE_NONE,
    :BLEND_MODE_REVERSE_SUBTRACT,
    :BLEND_MODE_SUBTRACT
])
@document BLEND_MODE_ADD "TODO"
@document BLEND_MODE_MAX "TODO"
@document BLEND_MODE_MIN "TODO"
@document BLEND_MODE_MULTIPLY "TODO"
@document BLEND_MODE_NONE "TODO"
@document BLEND_MODE_REVERSE_SUBTRACT "TODO"
@document BLEND_MODE_SUBTRACT "TODO"

@document ButtonID enum_docs(:ButtonID,
    "TODO", [
    :BUTTON_ID_ANY,
    :BUTTON_ID_BUTTON_01,
    :BUTTON_ID_BUTTON_02,
    :BUTTON_ID_BUTTON_03,
    :BUTTON_ID_BUTTON_04,
    :BUTTON_ID_BUTTON_05,
    :BUTTON_ID_BUTTON_06,
    :BUTTON_ID_BUTTON_07,
    :BUTTON_ID_BUTTON_08,
    :BUTTON_ID_BUTTON_09,
    :BUTTON_ID_NONE
])
@document BUTTON_ID_ANY "TODO"
@document BUTTON_ID_BUTTON_01 "TODO"
@document BUTTON_ID_BUTTON_02 "TODO"
@document BUTTON_ID_BUTTON_03 "TODO"
@document BUTTON_ID_BUTTON_04 "TODO"
@document BUTTON_ID_BUTTON_05 "TODO"
@document BUTTON_ID_BUTTON_06 "TODO"
@document BUTTON_ID_BUTTON_07 "TODO"
@document BUTTON_ID_BUTTON_08 "TODO"
@document BUTTON_ID_BUTTON_09 "TODO"
@document BUTTON_ID_NONE "TODO"

@document CheckButtonState enum_docs(:CheckButtonState,
    "TODO", [
    :CHECK_BUTTON_STATE_ACTIVE,
    :CHECK_BUTTON_STATE_INACTIVE,
    :CHECK_BUTTON_STATE_INCONSISTENT
])
@document CHECK_BUTTON_STATE_ACTIVE "TODO"
@document CHECK_BUTTON_STATE_INACTIVE "TODO"
@document CHECK_BUTTON_STATE_INCONSISTENT "TODO"

@document CornerPlacement enum_docs(:CornerPlacement,
    "TODO", [
    :CORNER_PLACEMENT_BOTTOM_LEFT,
    :CORNER_PLACEMENT_BOTTOM_RIGHT,
    :CORNER_PLACEMENT_TOP_LEFT,
    :CORNER_PLACEMENT_TOP_RIGHT
])
@document CORNER_PLACEMENT_BOTTOM_LEFT "TODO"
@document CORNER_PLACEMENT_BOTTOM_RIGHT "TODO"
@document CORNER_PLACEMENT_TOP_LEFT "TODO"
@document CORNER_PLACEMENT_TOP_RIGHT "TODO"

@document CursorType enum_docs(:CursorType,
    "TODO", [
    :CURSOR_TYPE_ALL_SCROLL,
    :CURSOR_TYPE_CELL,
    :CURSOR_TYPE_COLUMN_RESIZE,
    :CURSOR_TYPE_CONTEXT_MENU,
    :CURSOR_TYPE_CROSSHAIR,
    :CURSOR_TYPE_DEFAULT,
    :CURSOR_TYPE_EAST_RESIZE,
    :CURSOR_TYPE_GRAB,
    :CURSOR_TYPE_GRABBING,
    :CURSOR_TYPE_HELP,
    :CURSOR_TYPE_MOVE,
    :CURSOR_TYPE_NONE,
    :CURSOR_TYPE_NORTH_EAST_RESIZE,
    :CURSOR_TYPE_NORTH_RESIZE,
    :CURSOR_TYPE_NORTH_WEST_RESIZE,
    :CURSOR_TYPE_NOT_ALLOWED,
    :CURSOR_TYPE_POINTER,
    :CURSOR_TYPE_PROGRESS,
    :CURSOR_TYPE_ROW_RESIZE,
    :CURSOR_TYPE_SOUTH_EAST_RESIZE,
    :CURSOR_TYPE_SOUTH_RESIZE,
    :CURSOR_TYPE_SOUTH_WEST_RESIZE,
    :CURSOR_TYPE_TEXT,
    :CURSOR_TYPE_WAIT,
    :CURSOR_TYPE_WEST_RESIZE,
    :CURSOR_TYPE_ZOOM_IN,
    :CURSOR_TYPE_ZOOM_OUT
])
@document CURSOR_TYPE_ALL_SCROLL "TODO"
@document CURSOR_TYPE_CELL "TODO"
@document CURSOR_TYPE_COLUMN_RESIZE "TODO"
@document CURSOR_TYPE_CONTEXT_MENU "TODO"
@document CURSOR_TYPE_CROSSHAIR "TODO"
@document CURSOR_TYPE_DEFAULT "TODO"
@document CURSOR_TYPE_EAST_RESIZE "TODO"
@document CURSOR_TYPE_GRAB "TODO"
@document CURSOR_TYPE_GRABBING "TODO"
@document CURSOR_TYPE_HELP "TODO"
@document CURSOR_TYPE_MOVE "TODO"
@document CURSOR_TYPE_NONE "TODO"
@document CURSOR_TYPE_NORTH_EAST_RESIZE "TODO"
@document CURSOR_TYPE_NORTH_RESIZE "TODO"
@document CURSOR_TYPE_NORTH_WEST_RESIZE "TODO"
@document CURSOR_TYPE_NOT_ALLOWED "TODO"
@document CURSOR_TYPE_POINTER "TODO"
@document CURSOR_TYPE_PROGRESS "TODO"
@document CURSOR_TYPE_ROW_RESIZE "TODO"
@document CURSOR_TYPE_SOUTH_EAST_RESIZE "TODO"
@document CURSOR_TYPE_SOUTH_RESIZE "TODO"
@document CURSOR_TYPE_SOUTH_WEST_RESIZE "TODO"
@document CURSOR_TYPE_TEXT "TODO"
@document CURSOR_TYPE_WAIT "TODO"
@document CURSOR_TYPE_WEST_RESIZE "TODO"
@document CURSOR_TYPE_ZOOM_IN "TODO"
@document CURSOR_TYPE_ZOOM_OUT "TODO"

@document DeviceAxis enum_docs(:DeviceAxis,
    "TODO", [
    :DEVICE_AXIS_DELTA_X,
    :DEVICE_AXIS_DELTA_Y,
    :DEVICE_AXIS_DISTANCE,
    :DEVICE_AXIS_PRESSURE,
    :DEVICE_AXIS_ROTATION,
    :DEVICE_AXIS_SLIDER,
    :DEVICE_AXIS_WHEEL,
    :DEVICE_AXIS_X,
    :DEVICE_AXIS_X_TILT,
    :DEVICE_AXIS_Y,
    :DEVICE_AXIS_Y_TILT
])
@document DEVICE_AXIS_DELTA_X "TODO"
@document DEVICE_AXIS_DELTA_Y "TODO"
@document DEVICE_AXIS_DISTANCE "TODO"
@document DEVICE_AXIS_PRESSURE "TODO"
@document DEVICE_AXIS_ROTATION "TODO"
@document DEVICE_AXIS_SLIDER "TODO"
@document DEVICE_AXIS_WHEEL "TODO"
@document DEVICE_AXIS_X "TODO"
@document DEVICE_AXIS_X_TILT "TODO"
@document DEVICE_AXIS_Y "TODO"
@document DEVICE_AXIS_Y_TILT "TODO"

@document EllipsizeMode enum_docs(:EllipsizeMode,
    "TODO", [
    :ELLIPSIZE_MODE_END,
    :ELLIPSIZE_MODE_MIDDLE,
    :ELLIPSIZE_MODE_NONE,
    :ELLIPSIZE_MODE_START
])
@document ELLIPSIZE_MODE_END "TODO"
@document ELLIPSIZE_MODE_MIDDLE "TODO"
@document ELLIPSIZE_MODE_NONE "TODO"
@document ELLIPSIZE_MODE_START "TODO"

@document FileChooserAction enum_docs(:FileChooserAction,
    "TODO", [
    :FILE_CHOOSER_ACTION_OPEN_FILE,
    :FILE_CHOOSER_ACTION_OPEN_MULTIPLE_FILES,
    :FILE_CHOOSER_ACTION_SAVE,
    :FILE_CHOOSER_ACTION_SELECT_FOLDER,
    :FILE_CHOOSER_ACTION_SELECT_MULTIPLE_FOLDERS
])
@document FILE_CHOOSER_ACTION_OPEN_FILE "TODO"
@document FILE_CHOOSER_ACTION_OPEN_MULTIPLE_FILES "TODO"
@document FILE_CHOOSER_ACTION_SAVE "TODO"
@document FILE_CHOOSER_ACTION_SELECT_FOLDER "TODO"
@document FILE_CHOOSER_ACTION_SELECT_MULTIPLE_FOLDERS "TODO"

@document FileMonitorEvent enum_docs(:FileMonitorEvent,
    "TODO", [
    :FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED,
    :FILE_MONITOR_EVENT_CHANGED,
    :FILE_MONITOR_EVENT_CHANGES_DONE_HINT,
    :FILE_MONITOR_EVENT_CREATED,
    :FILE_MONITOR_EVENT_DELETED,
    :FILE_MONITOR_EVENT_MOVED_IN,
    :FILE_MONITOR_EVENT_MOVED_OUT,
    :FILE_MONITOR_EVENT_RENAMED
])
@document FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED "TODO"
@document FILE_MONITOR_EVENT_CHANGED "TODO"
@document FILE_MONITOR_EVENT_CHANGES_DONE_HINT "TODO"
@document FILE_MONITOR_EVENT_CREATED "TODO"
@document FILE_MONITOR_EVENT_DELETED "TODO"
@document FILE_MONITOR_EVENT_MOVED_IN "TODO"
@document FILE_MONITOR_EVENT_MOVED_OUT "TODO"
@document FILE_MONITOR_EVENT_RENAMED "TODO"

@document InterpolationType enum_docs(:InterpolationType,
    "TODO", [
    :INTERPOLATION_TYPE_BILINEAR,
    :INTERPOLATION_TYPE_HYPERBOLIC,
    :INTERPOLATION_TYPE_NEAREST,
    :INTERPOLATION_TYPE_TILES
])
@document INTERPOLATION_TYPE_BILINEAR "TODO"
@document INTERPOLATION_TYPE_HYPERBOLIC "TODO"
@document INTERPOLATION_TYPE_NEAREST "TODO"
@document INTERPOLATION_TYPE_TILES "TODO"

@document JustifyMode enum_docs(:JustifyMode,
    "TODO", [
    :JUSTIFY_MODE_CENTER,
    :JUSTIFY_MODE_FILL,
    :JUSTIFY_MODE_LEFT,
    :JUSTIFY_MODE_RIGHT
])
@document JUSTIFY_MODE_CENTER "TODO"
@document JUSTIFY_MODE_FILL "TODO"
@document JUSTIFY_MODE_LEFT "TODO"
@document JUSTIFY_MODE_RIGHT "TODO"

@document LabelWrapMode enum_docs(:LabelWrapMode,
    "TODO", [
    :LABEL_WRAP_MODE_NONE,
    :LABEL_WRAP_MODE_ONLY_ON_CHAR,
    :LABEL_WRAP_MODE_ONLY_ON_WORD,
    :LABEL_WRAP_MODE_WORD_OR_CHAR
])
@document LABEL_WRAP_MODE_NONE "TODO"
@document LABEL_WRAP_MODE_ONLY_ON_CHAR "TODO"
@document LABEL_WRAP_MODE_ONLY_ON_WORD "TODO"
@document LABEL_WRAP_MODE_WORD_OR_CHAR "TODO"

@document LevelBarMode enum_docs(:LevelBarMode,
    "TODO", [
    :LEVEL_BAR_MODE_CONTINUOUS,
    :LEVEL_BAR_MODE_DISCRETE
])
@document LEVEL_BAR_MODE_CONTINUOUS "TODO"
@document LEVEL_BAR_MODE_DISCRETE "TODO"

@document Orientation enum_docs(:Orientation,
    "TODO", [
    :ORIENTATION_HORIZONTAL,
    :ORIENTATION_VERTICAL
])
@document ORIENTATION_HORIZONTAL "TODO"
@document ORIENTATION_VERTICAL "TODO"

@document PanDirection enum_docs(:PanDirection,
    "TODO", [
    :PAN_DIRECTION_DOWN,
    :PAN_DIRECTION_LEFT,
    :PAN_DIRECTION_RIGHT,
    :PAN_DIRECTION_UP
])
@document PAN_DIRECTION_DOWN "TODO"
@document PAN_DIRECTION_LEFT "TODO"
@document PAN_DIRECTION_RIGHT "TODO"
@document PAN_DIRECTION_UP "TODO"

@document ProgressBarDisplayMode enum_docs(:ProgressBarDisplayMode,
    "TODO", [
    :PROGRESS_BAR_DISPLAY_MODE_SHOW_PERCENTAGE,
    :PROGRESS_BAR_DISPLAY_MODE_SHOW_TEXT
])
@document PROGRESS_BAR_DISPLAY_MODE_SHOW_PERCENTAGE "TODO"
@document PROGRESS_BAR_DISPLAY_MODE_SHOW_TEXT "TODO"

@document PropagationPhase enum_docs(:PropagationPhase,
    "TODO", [
    :PROPAGATION_PHASE_BUBBLE,
    :PROPAGATION_PHASE_CAPTURE,
    :PROPAGATION_PHASE_NONE,
    :PROPAGATION_PHASE_TARGET
])
@document PROPAGATION_PHASE_BUBBLE "TODO"
@document PROPAGATION_PHASE_CAPTURE "TODO"
@document PROPAGATION_PHASE_NONE "TODO"
@document PROPAGATION_PHASE_TARGET "TODO"

@document RelativePosition enum_docs(:RelativePosition,
    "TODO", [
    :RELATIVE_POSITION_ABOVE,
    :RELATIVE_POSITION_BELOW,
    :RELATIVE_POSITION_LEFT_OF,
    :RELATIVE_POSITION_RIGHT_OF
])
@document RELATIVE_POSITION_ABOVE "TODO"
@document RELATIVE_POSITION_BELOW "TODO"
@document RELATIVE_POSITION_LEFT_OF "TODO"
@document RELATIVE_POSITION_RIGHT_OF "TODO"

@document RevealerTransitionType enum_docs(:RevealerTransitionType,
    "TODO", [
    :REVEALER_TRANSITION_TYPE_CROSSFADE,
    :REVEALER_TRANSITION_TYPE_NONE,
    :REVEALER_TRANSITION_TYPE_SLIDE_DOWN,
    :REVEALER_TRANSITION_TYPE_SLIDE_LEFT,
    :REVEALER_TRANSITION_TYPE_SLIDE_RIGHT,
    :REVEALER_TRANSITION_TYPE_SLIDE_UP,
    :REVEALER_TRANSITION_TYPE_SWING_DOWN,
    :REVEALER_TRANSITION_TYPE_SWING_LEFT,
    :REVEALER_TRANSITION_TYPE_SWING_RIGHT,
    :REVEALER_TRANSITION_TYPE_SWING_UP
])
@document REVEALER_TRANSITION_TYPE_CROSSFADE "TODO"
@document REVEALER_TRANSITION_TYPE_NONE "TODO"
@document REVEALER_TRANSITION_TYPE_SLIDE_DOWN "TODO"
@document REVEALER_TRANSITION_TYPE_SLIDE_LEFT "TODO"
@document REVEALER_TRANSITION_TYPE_SLIDE_RIGHT "TODO"
@document REVEALER_TRANSITION_TYPE_SLIDE_UP "TODO"
@document REVEALER_TRANSITION_TYPE_SWING_DOWN "TODO"
@document REVEALER_TRANSITION_TYPE_SWING_LEFT "TODO"
@document REVEALER_TRANSITION_TYPE_SWING_RIGHT "TODO"
@document REVEALER_TRANSITION_TYPE_SWING_UP "TODO"

@document ScrollType enum_docs(:ScrollType,
    "TODO", [
    :SCROLL_TYPE_JUMP,
    :SCROLL_TYPE_NONE,
    :SCROLL_TYPE_PAGE_BACKWARD,
    :SCROLL_TYPE_PAGE_DOWN,
    :SCROLL_TYPE_PAGE_FORWARD,
    :SCROLL_TYPE_PAGE_LEFT,
    :SCROLL_TYPE_PAGE_RIGHT,
    :SCROLL_TYPE_PAGE_UP,
    :SCROLL_TYPE_SCROLL_END,
    :SCROLL_TYPE_SCROLL_START,
    :SCROLL_TYPE_STEP_BACKWARD,
    :SCROLL_TYPE_STEP_DOWN,
    :SCROLL_TYPE_STEP_FORWARD,
    :SCROLL_TYPE_STEP_LEFT,
    :SCROLL_TYPE_STEP_RIGHT,
    :SCROLL_TYPE_STEP_UP
])
@document SCROLL_TYPE_JUMP "TODO"
@document SCROLL_TYPE_NONE "TODO"
@document SCROLL_TYPE_PAGE_BACKWARD "TODO"
@document SCROLL_TYPE_PAGE_DOWN "TODO"
@document SCROLL_TYPE_PAGE_FORWARD "TODO"
@document SCROLL_TYPE_PAGE_LEFT "TODO"
@document SCROLL_TYPE_PAGE_RIGHT "TODO"
@document SCROLL_TYPE_PAGE_UP "TODO"
@document SCROLL_TYPE_SCROLL_END "TODO"
@document SCROLL_TYPE_SCROLL_START "TODO"
@document SCROLL_TYPE_STEP_BACKWARD "TODO"
@document SCROLL_TYPE_STEP_DOWN "TODO"
@document SCROLL_TYPE_STEP_FORWARD "TODO"
@document SCROLL_TYPE_STEP_LEFT "TODO"
@document SCROLL_TYPE_STEP_RIGHT "TODO"
@document SCROLL_TYPE_STEP_UP "TODO"

@document ScrollbarVisibilityPolicy enum_docs(:ScrollbarVisibilityPolicy,
    "TODO", [
    :SCROLLBAR_VISIBILITY_POLICY_ALWAYS,
    :SCROLLBAR_VISIBILITY_POLICY_AUTOMATIC,
    :SCROLLBAR_VISIBILITY_POLICY_NEVER
])
@document SCROLLBAR_VISIBILITY_POLICY_ALWAYS "TODO"
@document SCROLLBAR_VISIBILITY_POLICY_AUTOMATIC "TODO"
@document SCROLLBAR_VISIBILITY_POLICY_NEVER "TODO"

@document SectionFormat enum_docs(:SectionFormat,
    "TODO", [
    :SECTION_FORMAT_CIRCULAR_BUTTONS,
    :SECTION_FORMAT_HORIZONTAL_BUTTONS,
    :SECTION_FORMAT_HORIZONTAL_BUTTONS_LEFT_TO_RIGHT,
    :SECTION_FORMAT_HORIZONTAL_BUTTONS_RIGHT_TO_LEFT,
    :SECTION_FORMAT_INLINE_BUTTONS,
    :SECTION_FORMAT_NORMAL
])
@document SECTION_FORMAT_CIRCULAR_BUTTONS "TODO"
@document SECTION_FORMAT_HORIZONTAL_BUTTONS "TODO"
@document SECTION_FORMAT_HORIZONTAL_BUTTONS_LEFT_TO_RIGHT "TODO"
@document SECTION_FORMAT_HORIZONTAL_BUTTONS_RIGHT_TO_LEFT "TODO"
@document SECTION_FORMAT_INLINE_BUTTONS "TODO"
@document SECTION_FORMAT_NORMAL "TODO"

@document SelectionMode enum_docs(:SelectionMode,
    "TODO", [
    :SELECTION_MODE_MULTIPLE,
    :SELECTION_MODE_NONE,
    :SELECTION_MODE_SINGLE
])
@document SELECTION_MODE_MULTIPLE "TODO"
@document SELECTION_MODE_NONE "TODO"
@document SELECTION_MODE_SINGLE "TODO"

@document ShaderType enum_docs(:ShaderType,
    "TODO", [
    :SHADER_TYPE_FRAGMENT,
    :SHADER_TYPE_VERTEX
])
@document SHADER_TYPE_FRAGMENT "TODO"
@document SHADER_TYPE_VERTEX "TODO"

@document ShortcutScope enum_docs(:ShortcutScope,
    "TODO", [
    :SHORTCUT_SCOPE_GLOBAL,
    :SHORTCUT_SCOPE_LOCAL,
    :SHORTCUT_SCOPE_MANAGED
])
@document SHORTCUT_SCOPE_GLOBAL "TODO"
@document SHORTCUT_SCOPE_LOCAL "TODO"
@document SHORTCUT_SCOPE_MANAGED "TODO"

@document StackTransitionType enum_docs(:StackTransitionType,
    "TODO", [
    :STACK_TRANSITION_TYPE_CROSSFADE,
    :STACK_TRANSITION_TYPE_NONE,
    :STACK_TRANSITION_TYPE_OVER_DOWN,
    :STACK_TRANSITION_TYPE_OVER_LEFT,
    :STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT,
    :STACK_TRANSITION_TYPE_OVER_RIGHT,
    :STACK_TRANSITION_TYPE_OVER_UP,
    :STACK_TRANSITION_TYPE_OVER_UP_DOWN,
    :STACK_TRANSITION_TYPE_ROTATE_LEFT,
    :STACK_TRANSITION_TYPE_ROTATE_LEFT_RIGHT,
    :STACK_TRANSITION_TYPE_ROTATE_RIGHT,
    :STACK_TRANSITION_TYPE_SLIDE_DOWN,
    :STACK_TRANSITION_TYPE_SLIDE_LEFT,
    :STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT,
    :STACK_TRANSITION_TYPE_SLIDE_RIGHT,
    :STACK_TRANSITION_TYPE_SLIDE_UP,
    :STACK_TRANSITION_TYPE_SLIDE_UP_DOWN,
    :STACK_TRANSITION_TYPE_UNDER_DOWN,
    :STACK_TRANSITION_TYPE_UNDER_LEFT,
    :STACK_TRANSITION_TYPE_UNDER_RIGHT,
    :STACK_TRANSITION_TYPE_UNDER_UP
])
@document STACK_TRANSITION_TYPE_CROSSFADE "TODO"
@document STACK_TRANSITION_TYPE_NONE "TODO"
@document STACK_TRANSITION_TYPE_OVER_DOWN "TODO"
@document STACK_TRANSITION_TYPE_OVER_LEFT "TODO"
@document STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT "TODO"
@document STACK_TRANSITION_TYPE_OVER_RIGHT "TODO"
@document STACK_TRANSITION_TYPE_OVER_UP "TODO"
@document STACK_TRANSITION_TYPE_OVER_UP_DOWN "TODO"
@document STACK_TRANSITION_TYPE_ROTATE_LEFT "TODO"
@document STACK_TRANSITION_TYPE_ROTATE_LEFT_RIGHT "TODO"
@document STACK_TRANSITION_TYPE_ROTATE_RIGHT "TODO"
@document STACK_TRANSITION_TYPE_SLIDE_DOWN "TODO"
@document STACK_TRANSITION_TYPE_SLIDE_LEFT "TODO"
@document STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT "TODO"
@document STACK_TRANSITION_TYPE_SLIDE_RIGHT "TODO"
@document STACK_TRANSITION_TYPE_SLIDE_UP "TODO"
@document STACK_TRANSITION_TYPE_SLIDE_UP_DOWN "TODO"
@document STACK_TRANSITION_TYPE_UNDER_DOWN "TODO"
@document STACK_TRANSITION_TYPE_UNDER_LEFT "TODO"
@document STACK_TRANSITION_TYPE_UNDER_RIGHT "TODO"
@document STACK_TRANSITION_TYPE_UNDER_UP "TODO"

@document TextureScaleMode enum_docs(:TextureScaleMode,
    "TODO", [
    :TEXTURE_SCALE_MODE_LINEAR,
    :TEXTURE_SCALE_MODE_NEAREST
])
@document TEXTURE_SCALE_MODE_LINEAR "TODO"
@document TEXTURE_SCALE_MODE_NEAREST "TODO"

@document TextureWrapMode enum_docs(:TextureWrapMode,
    "TODO", [
    :TEXTURE_WRAP_MODE_MIRROR,
    :TEXTURE_WRAP_MODE_ONE,
    :TEXTURE_WRAP_MODE_REPEAT,
    :TEXTURE_WRAP_MODE_STRETCH,
    :TEXTURE_WRAP_MODE_ZERO
])
@document TEXTURE_WRAP_MODE_MIRROR "TODO"
@document TEXTURE_WRAP_MODE_ONE "TODO"
@document TEXTURE_WRAP_MODE_REPEAT "TODO"
@document TEXTURE_WRAP_MODE_STRETCH "TODO"
@document TEXTURE_WRAP_MODE_ZERO "TODO"

@document TickCallbackResult enum_docs(:TickCallbackResult,
    "TODO", [
    :TICK_CALLBACK_RESULT_CONTINUE,
    :TICK_CALLBACK_RESULT_DISCONTINUE
])
@document TICK_CALLBACK_RESULT_CONTINUE "TODO"
@document TICK_CALLBACK_RESULT_DISCONTINUE "TODO"

@document ToolType enum_docs(:ToolType,
    "TODO", [
    :TOOL_TYPE_AIRBRUSH,
    :TOOL_TYPE_BRUSH,
    :TOOL_TYPE_ERASER,
    :TOOL_TYPE_LENS,
    :TOOL_TYPE_MOUSE,
    :TOOL_TYPE_PEN,
    :TOOL_TYPE_PENCIL,
    :TOOL_TYPE_UNKNOWN
])
@document TOOL_TYPE_AIRBRUSH "TODO"
@document TOOL_TYPE_BRUSH "TODO"
@document TOOL_TYPE_ERASER "TODO"
@document TOOL_TYPE_LENS "TODO"
@document TOOL_TYPE_MOUSE "TODO"
@document TOOL_TYPE_PEN "TODO"
@document TOOL_TYPE_PENCIL "TODO"
@document TOOL_TYPE_UNKNOWN "TODO"

@document WindowCloseRequestResult enum_docs(:WindowCloseRequestResult,
    "TODO", [
    :WINDOW_CLOSE_REQUEST_RESULT_ALLOW_CLOSE,
    :WINDOW_CLOSE_REQUEST_RESULT_PREVENT_CLOSE
])
@document WINDOW_CLOSE_REQUEST_RESULT_ALLOW_CLOSE "TODO"
@document WINDOW_CLOSE_REQUEST_RESULT_PREVENT_CLOSE "TODO"

