name: CI
on:
  push:
  pull_request:  
  
defaults:
  run:
    shell: bash
    
jobs:
    test:
      name: Julia ${{ matrix.julia-version }} ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          julia-version:
            - "1.7"
            - "1.9"
            - "1"
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest
          julia-arch:
            - x64
          include:
            - os: ubuntu-latest
              prefix: xvfb-run
      steps: 
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}
            show-versioninfo: true
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@v1
  
    docs:
      name: Documentation
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: '1.7'
        - run: julia --project=docs -e '
            using Pkg;
            Pkg.develop(PackageSpec(; path=pwd()));
            Pkg.instantiate();
            Pkg.add(url=\"https://github.com/JuliaDocs/Documenter.jl\");'
        - run: julia --project=docs docs/make.jl
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
